services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres123@auth-db:5432/auth_db
      SECRET_KEY: super-secret-key
      ALGORITHM: HS256
    depends_on:
      auth-db:
        condition: service_healthy

  tutors-service:
    build: ./services/tutors-service
    container_name: tutors-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres123@tutors-db:5432/tutors_db
      SECRET_KEY: super-secret-key
      ALGORITHM: HS256
    depends_on:
      tutors-db:
        condition: service_healthy

  tutors-db:
    image: postgres:15
    container_name: tutors-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tutors_db
    volumes:
      - tutors_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  auth_db_data:
  tutors_db_data:
