services:
  # =========================
  # DATABASES (STATEFUL)
  # =========================
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-attendance:
    image: postgres:16-alpine
    container_name: postgres-attendance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_attendance_data:/var/lib/postgresql/data

  # =========================
  # MICROSERVICES (STATELESS)
  # =========================
  auth-service:
    build:
      context: ../apps/auth-service
      dockerfile: ../../infra/docker/auth-service.Dockerfile
    container_name: auth-service
    env_file:
      - ../apps/auth-service/.env
    depends_on:
      - postgres-auth
    ports:
      - "3000:3000"

  attendance-service:
    build:
      context: ../apps/attendance-service
      dockerfile: ../../infra/docker/attendance-service.Dockerfile
    container_name: attendance-service
    env_file:
      - ../apps/attendance-service/.env
    depends_on:
      - postgres-attendance
    ports:
      - "3002:3002"

  api-gateway:
    build:
      context: ../apps/api-gateway
      dockerfile: ../../infra/docker/api-gateway.Dockerfile
    container_name: api-gateway
    env_file:
      - ../apps/api-gateway/.env
    depends_on:
      - auth-service
      - attendance-service
    ports:
      - "3001:3001"

volumes:
  postgres_auth_data:
  postgres_attendance_data:
