services:
  # =========================
  # DATABASES (STATEFUL)
  # =========================
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-attendance:
    image: postgres:16-alpine
    container_name: postgres-attendance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_attendance_data:/var/lib/postgresql/data

  postgres-tracking:
    image: postgres:16-alpine
    container_name: postgres-tracking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracking_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_tracking_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # =========================
  # MESSAGING (QA)
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # LISTENERS
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # =========================
  # MICROSERVICES (STATELESS)
  # =========================
  auth-service:
    build:
      context: ../apps/auth-service
      dockerfile: ../../infra/docker/auth-service.Dockerfile
    container_name: auth-service
    env_file:
      - ../apps/auth-service/.env
    depends_on:
      - postgres-auth
    ports:
      - "3000:3000"

  attendance-service:
    build:
      context: ../apps/attendance-service
      dockerfile: ../../infra/docker/attendance-service.Dockerfile
    container_name: attendance-service
    env_file:
      - ../apps/attendance-service/.env
    depends_on:
      - postgres-attendance
    ports:
      - "3002:3002"

  tracking-service:
    build:
      context: ../apps/tracking-service
      dockerfile: ../../infra/docker/tracking-service.Dockerfile
    container_name: tracking-service
    env_file:
      - ../apps/tracking-service/.env
    depends_on:
      - postgres-tracking
      - redis
    ports:
      - "3003:3003"

  api-gateway:
    build:
      context: ../apps/api-gateway
      dockerfile: ../../infra/docker/api-gateway.Dockerfile
    container_name: api-gateway
    env_file:
      - ../apps/api-gateway/.env
    depends_on:
      - auth-service
      - attendance-service
      - tracking-service
    ports:
      - "3001:3001"

volumes:
  postgres_auth_data:
  postgres_attendance_data:
  postgres_tracking_data:
