services:
  # =========================
  # DATABASES (STATEFUL)
  # =========================
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-attendance:
    image: postgres:16-alpine
    container_name: postgres-attendance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_attendance_data:/var/lib/postgresql/data

  postgres-tracking:
    image: postgres:16-alpine
    container_name: postgres-tracking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracking_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_tracking_data:/var/lib/postgresql/data

  postgres-children:
    image: postgres:16-alpine
    container_name: postgres-children
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: children_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_children_data:/var/lib/postgresql/data
    
  postgres-tutors:
    image: postgres:16-alpine
    container_name: postgres-tutors
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tutors_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_tutors_data:/var/lib/postgresql/data

  postgres-staff:
    image: postgres:16-alpine
    container_name: postgres-staff
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staff_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_staff_data:/var/lib/postgresql/data



  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
  
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
  

  # =========================
  # KAFKA / ZOOKEEPER
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  postgres-files:
    image: postgres:16-alpine
    container_name: postgres-files
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: files_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_files_data:/var/lib/postgresql/data


  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb --ignore-existing local/daycare-files &&
      mc anonymous set public local/daycare-files &&
      echo 'Bucket ready';
      "

# =========================
# FRONTEND
# =========================
  web:
    build:
      context: ..
      dockerfile: infra/docker/web.Dockerfile
    container_name: web
    env_file:
      - ../clients/web/.env.docker
    ports:
      - "3009:3009"
    environment:
      # Ajusta base URL para llamar al gateway (mismo host dentro docker)
      NEXT_PUBLIC_API_BASE_URL: "http://gateway"
    depends_on:
      - auth-service
      - attendance-service
      - tracking-service
      - children-service
      - tutors-service
      - staff-service
      - files-service
      - notifications-service

  # =========================
  # API GATEWAY
  # =========================
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - auth-service
      - attendance-service
      - tracking-service
      - notifications-service
      - children-service
      - tutors-service
      - staff-service
      - files-service


  # =========================
  # MICROSERVICES (STATELESS)
  # =========================
  auth-service:
    build:
      context: ../apps/auth-service
      dockerfile: ../../infra/docker/auth-service.Dockerfile
    container_name: auth-service
    env_file:
      - ../apps/auth-service/.env
    depends_on:
      - postgres-auth
    ports:
      - "3000:3000"

  attendance-service:
    build:
      context: ../apps/attendance-service
      dockerfile: ../../infra/docker/attendance-service.Dockerfile
    container_name: attendance-service
    env_file:
      - ../apps/attendance-service/.env
    depends_on:
      - postgres-attendance
      - kafka
    ports:
      - "3002:3002"

  tracking-service:
    build:
      context: ../apps/tracking-service
      dockerfile: ../../infra/docker/tracking-service.Dockerfile
    container_name: tracking-service
    env_file:
      - ../apps/tracking-service/.env
    depends_on:
      - postgres-tracking
      - redis
      - kafka
      - dynamodb
    ports:
      - "3003:3003"


  notifications-service:
    build:
      context: ../apps/notifications-service
      dockerfile: ../../infra/docker/notifications-service.Dockerfile
    container_name: notifications-service
    env_file:
      - ../apps/notifications-service/.env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3004:3004"

  children-service:
    build:
      context: ../apps/children-service
      dockerfile: ../../infra/docker/children-service.Dockerfile
    container_name: children-service
    env_file:
      - ../apps/children-service/.env
    depends_on:
      - postgres-children
    ports:
      - "3005:3005"
    
  tutors-service:
    build:
      context: ../apps/tutors-service
      dockerfile: ../../infra/docker/tutors-service.Dockerfile
    container_name: tutors-service
    env_file:
      - ../apps/tutors-service/.env
    depends_on:
      - postgres-tutors
    ports:
      - "3006:3006"

  staff-service:
    build:
      context: ../apps/staff-service
      dockerfile: ../../infra/docker/staff-service.Dockerfile
    container_name: staff-service
    env_file:
      - ../apps/staff-service/.env
    depends_on:
      - postgres-staff
    ports:
      - "3007:3007"

  files-service:
    build:
      context: ../apps/files-service
      dockerfile: ../../infra/docker/files-service.Dockerfile
    container_name: files-service
    env_file:
      - ../apps/files-service/.env
    depends_on:
      - postgres-files
      - minio
    ports:
      - "3008:3008"



 # =========================
  # VOLUMES
  # ========================= 

volumes:
  postgres_auth_data:
  postgres_attendance_data:
  postgres_tracking_data:
  postgres_children_data:
  rabbitmq_data:
  postgres_tutors_data:
  postgres_staff_data:
  postgres_files_data:
  minio_data:



